### ISSUE TITLE
lr_scheduler

### ISSUE THREAD

**Issue by lironghua318** [KevinMusgrave/powerful_benchmarker#4]
**hello,i can't add lr_scheduler**

**config_optimizers/default.yaml i try to add  CosineAnnealingLR**

optimizers:
  trunk_optimizer:
    Adam:
      lr: 0.00001
      weight_decay: 0.00005
    scheduler:
      CosineAnnealingLR:
        T_max: 10
  embedder_optimizer:
    Adam:
      lr: 0.00001
      weight_decay: 0.00005
    scheduler:
      CosineAnnealingLR:
        T_max: 10

**but i got** 

Traceback (most recent call last):
  File "/home/lironghua/.pycharm_helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/home/lironghua/.pycharm_helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/lironghua/.pycharm_helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/lironghua/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/lironghua/powerful_benchmarker-master/run.py", line 95, in <module>
    run_new_experiment(YR, config_foldernames)
  File "/home/lironghua/powerful_benchmarker-master/run.py", line 83, in run_new_experiment
    run(args)
  File "/home/lironghua/powerful_benchmarker-master/run.py", line 45, in run
    api_parser.run()
  File "/home/lironghua/powerful_benchmarker-master/api_parsers/base_api_parser.py", line 55, in run
    self.set_models_optimizers_losses()
  File "/home/lironghua/powerful_benchmarker-master/api_parsers/base_api_parser.py", line 316, in set_models_optimizers_losses
    self.set_optimizers()
  File "/home/lironghua/powerful_benchmarker-master/api_parsers/base_api_parser.py", line 113, in set_optimizers
    o, s, g = self.pytorch_getter.get_optimizer(param_source, yaml_dict=v)
  File "/home/lironghua/.conda/envs/metric/lib/python3.7/site-packages/easy_module_attribute_getter/pytorch_getter.py", line 49, in get_optimizer
    return_uninitialized=True
  File "/home/lironghua/.conda/envs/metric/lib/python3.7/site-packages/easy_module_attribute_getter/easy_module_attribute_getter.py", line 9, in get
    (class_name, params), = yaml_dict.items()
ValueError: too many values to unpack (expected 1)

**Comment by lironghua318** [comment]
now i  write  lr_scheduler in base_api_parser.py directly

**Comment by KevinMusgrave** [comment]
Hmm, I was able to run it. Here's how I have the yaml file formatted: 

```yaml
optimizers:
  trunk_optimizer:
    Adam:
      lr: 0.00001
      weight_decay: 0.00005
      scheduler:
        CosineAnnealingLR:
          T_max: 10
  embedder_optimizer:
    Adam:
      lr: 0.00001
      weight_decay: 0.00005
      scheduler:
        CosineAnnealingLR:
          T_max: 10
```
